- name: Build and Push Image
  run: |
    az acr login --name microhackregstacs20 --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
    docker build -t microhackregistry.azurecr.io/microhackapp:1 -f Dockerfile . &&
    docker push microhackregistry.azurecr.io/microhackapp:1
